name: Build and deploy Node.js app to Azure Web App - usf-autentication-prediction
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Build Client and Install Server Dependencies
        run: |
          # 1. Build React client
          echo "Building client..."
          cd client
          npm install
          npm run build
          
          # 2. Install server's production dependencies
          echo "Installing server dependencies..."
          cd ../server
          npm install --only=production

          # 3. Move client build into server folder
          # (Assuming your server is set up to serve static files from a 'public' folder)
          echo "Moving client build to server/public..."
          mv ../client/build ./public

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # Only upload the server folder, which now contains the client build
          path: server/ 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production' 
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: .