# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy Node.js app to Azure Web App - usf-autentication-prediction
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Build Client and Install Server Dependencies
        env:
          CI: false
        run: |
          # 1. Build React client
          echo "Building client..."
          cd client
          npm install
          npm run build
          # 2. Install server's production dependencies
          echo "Installing server dependencies..."
          cd ../server
          npm install --only=production
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            server/
            client/build/
  deploy:
    runs-on: ubuntu-latest
    needs: build
